### ISSUE TITLE
Remove the `required` field from CSV

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-management-ingress-operator#10]
Common services operators don’t need to specify `spec.customresourcedefinitions.required`  in their CSV.  

In the Q1 release, there is no dependency management from ODLM, all the required operators need to be added into `OperandRequest` instance.

In the Q2 release, operators will use `OperandRequest` to manage their own dependencies.

https://github.com/IBM/ibm-management-ingress-operator/blob/master/deploy/olm-catalog/ibm-management-ingress-operator/0.0.1/ibm-management-ingress-operator.v0.0.1.clusterserviceversion.yaml#L76

**Comment by liqlin2015** [comment]
Will be removed in this PR https://github.com/IBM/ibm-management-ingress-operator/pull/11
