### ISSUE TITLE
Issues when testing with the meta-operator

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-management-ingress-operator#6]
ImagePullBackOff when pulling `quay.io/opencloudio/ibm-management-ingress-operator:latest`

There is no image `quay.io/opencloudio/ibm-management-ingress-operator` in the quay.io/opencloudio yet.

![Screen Shot 2020-02-25 at 10 57 57 AM](https://user-images.githubusercontent.com/33276414/75264638-b4aea000-57bd-11ea-8c29-667c2ec946b1.png)

**Comment by liqlin2015** [comment]
Have changed the image to `ibmcom/icp-management-ingress:2.4.0` to workaround.
Still waiting for the decision where should push the operand images

**Comment by liqlin2015** [comment]
It was fixed now. We can close it.
